#! /bin/sh

##########################
#                        #
#   Author: adeecc       #
#   Date: 3 Jan, 2022    #
#                        #
##########################  

#### AUTOSTART ####
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.scripts/monitors.sh & 
nitrogen --restore &
dunst &
picom --config $HOME/.config/picom.conf &
nm-applet & 
$HOME/.config/polybar/bspwm.sh &

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 10

#### BSPWM configuration ####
bspc config border_width                    1
bspc config window_gap                      10
# bspc config single_monocle                false

bspc config split_ratio                     0.52
bspc config borderless_monocle              true
bspc config gapless_monocle                 true
bspc config remove_disabled_monitors        true
bspc config merge_overlapping_monitors      true
bspc config focus_follows_pointer           true

#### BSPWM coloring ####
# bspc config normal_border_color           "#fabd2f"
# bspc config active_border_color           "#fbf1c7f"
# bspc config focused_border_color          "#fbf1c7"
# bspc config presel_feedback_color         "#5e81ac"
# bspc config urgent_border_color           "#dd2727"