#! /bin/sh
##########################
#                        #
#   Author: adeecc       #
#   Date: 28 Aug, 2021   #
#                        #
##########################  

#### AUTOSTART ####

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.scripts/docked.sh & 
feh --bg-fill "/home/adeecc/Pictures/wallpapers/PLACES-ocean.jpg" &
dunst & 
picom --config /home/adeecc/.config/picom.conf &
nm-applet &
$HOME/.config/polybar/bspwm.sh &

# bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor eDP-1 -d I II III IV V
bspc monitor HDMI-1 -d I II III IV V

#### BSPWM configuration ####
bspc config border_radius                   8
bspc config border_width                    1
bspc config window_gap                      12
# bspc config single_monocle                false

bspc config split_ratio                     0.50
bspc config borderless_monocle              true
bspc config remove_disabled_monitors        true
bspc config merge_overlapping_monitors      true
bspc config focus_follows_pointer           true

#### BSPWM coloring ####
bspc config normal_border_color		      	"#fabd2f"
bspc config active_border_color	          	"#fbf1c7f"
bspc config focused_border_color	      	"#fbf1c7"
bspc config presel_feedback_color	      	"#5e81ac"
bspc config urgent_border_color 	      	"#dd2727"


